export const HOME_PAGE_LOADED = "HOME_PAGE_LOADED";
export const FETCH_ARTICLES_ALL = "FETCH_ARTICLES_ALL";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_START = "FETCH_START";

// Articles
export const ARTICLES_REQUEST = "ARTICLES_REQUEST";
export const ARTICLES_SUCESS = "ARTICLES_SUCCESS";
export const ARTICLES_FAILURE = "ARTICLES_FAILURE";
export const ADD_ARTICLES = "ADD_ARTICLES";
